# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./launchApi/launchApi.csproj
    - name: Build
      run: dotnet build ./launchApi/launchApicsproj --no-restore
    - name: Depcheck
      uses: dependency-check/Dependency-Check_Action@main
      id: Depcheck
      with:
        project: 'launchApi'
        path: '.'
        format: 'HTML'
        out: 'reports'
        args: #>
          #--failOnCVSS 7
          --enableRetired
    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
          name: Depcheck report
          path: reports
          if-no-files-found: error

  api-test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Run
        run: dotnet run ./launchApi/launchApi.csproj --no-restore
      - name: Prepare newman
        run: npm install -g newman
      - name: Run test with newman
        run: newman run ./tests/apiTests/launchApi.postman_collection.json --verbose 2>&1 | tee apiTest_report
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: Api test report
          path: apiTest_report
          if-no-files-found: error

 